import type { Metadata } from "next";
import { ConfigProvider } from "antd";
import theme from "../config/themeConfig";
import "./globals.css";

// 引入antd样式
import "antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayouchildrent({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ConfigProvider theme={theme}>{children}</ConfigProvider>
      </body>
    </html>
  );
}
